# Generated by Django 4.1.3 on 2023-11-02 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tablet", "0001_initial"),
        ("request", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="request",
            name="tablet",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="tablet.tablet",
            ),
        ),
    ]
