# Generated by Django 4.1.3 on 2023-11-15 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("request", "0003_alter_request_for_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="request",
            name="for_role",
            field=models.PositiveSmallIntegerField(
                choices=[(0, "Secretary"), (1, "Careworker")]
            ),
        ),
    ]
