# Generated by Django 4.1.3 on 2023-11-23 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("request", "0005_chatmessage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatmessage",
            name="request",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="request.request"
            ),
        ),
    ]
