# Generated by Django 4.1.3 on 2023-12-12 07:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("request", "0007_alter_request_for_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="request",
            name="staff",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="staff_requests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
