# Generated by Django 4.1.3 on 2024-01-28 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("request", "0008_request_staff"),
    ]

    operations = [
        migrations.RenameField(
            model_name="request",
            old_name="for_role",
            new_name="for_type",
        ),
    ]
