# Generated by Django 4.1.3 on 2024-01-28 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("request", "0009_rename_for_role_request_for_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="request",
            name="for_type",
            field=models.PositiveSmallIntegerField(
                choices=[(0, "Helper"), (1, "Nurse"), (2, "Doctor")], null=True
            ),
        ),
    ]
