# Generated by Django 4.1.3 on 2023-11-02 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staff",
            name="nfc",
            field=models.CharField(max_length=256, null=True),
        ),
    ]
