# Generated by Django 4.1.3 on 2023-11-03 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0002_alter_staff_nfc"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staff",
            name="role",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "Admin"),
                    (1, "Secretary"),
                    (2, "Helper"),
                    (3, "Nurse"),
                    (4, "Doctor"),
                ],
                null=True,
            ),
        ),
    ]
