# Generated by Django 4.1.3 on 2023-11-15 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0004_alter_staff_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="staff",
            name="type",
            field=models.PositiveSmallIntegerField(
                choices=[(0, "Secretary"), (1, "Careworker")], null=True
            ),
        ),
        migrations.AlterField(
            model_name="staff",
            name="role",
            field=models.PositiveSmallIntegerField(
                choices=[(0, "Secretary"), (1, "Careworker")], null=True
            ),
        ),
    ]
