# Generated by Django 4.1.3 on 2024-01-28 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0006_alter_staff_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staff",
            name="role",
            field=models.PositiveSmallIntegerField(
                choices=[(0, "Careworker"), (1, "Patient")], null=True
            ),
        ),
    ]
