# Generated by Django 4.1.3 on 2023-11-02 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=255, null=True)),
                ("last_name", models.CharField(max_length=255, null=True)),
                ("age", models.IntegerField(null=True)),
                ("doctor_first_visit", models.BooleanField(default=False)),
                (
                    "hospitalization",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Not Hospitalized"),
                            (1, "Hospitalized"),
                            (2, "Critical"),
                        ],
                        default=0,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MedicalExamination",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "state",
                    models.IntegerField(
                        choices=[(0, "Waiting"), (1, "Processing"), (2, "Finished")],
                        default=0,
                    ),
                ),
                ("time", models.DateTimeField(null=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medical_examinations",
                        to="patient.patient",
                    ),
                ),
            ],
        ),
    ]
