# Generated by Django 4.1.3 on 2023-12-11 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patient", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="patient",
            name="doctor_first_visit",
        ),
        migrations.RemoveField(
            model_name="patient",
            name="hospitalization",
        ),
        migrations.AddField(
            model_name="patient",
            name="medical_progress",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "Wait"),
                    (1, "CT"),
                    (2, "X-Ray"),
                    (3, "Blood"),
                    (4, "Doctor first visit"),
                    (5, "Out of the hospital"),
                ],
                default=0,
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="severity",
            field=models.PositiveSmallIntegerField(
                choices=[(0, "Low"), (1, "Middle"), (2, "High")], default=0
            ),
        ),
        migrations.DeleteModel(
            name="MedicalExamination",
        ),
    ]
