# Generated by Django 4.1.3 on 2023-12-10 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("settings", "0001_initial"),
        ("tablet", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tablet",
            name="room",
        ),
        migrations.AddField(
            model_name="tablet",
            name="area",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tablets",
                to="settings.area",
            ),
        ),
    ]
