# Generated by Django 4.1.3 on 2023-12-11 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tablet", "0002_remove_tablet_room_tablet_area"),
    ]

    operations = [
        migrations.AddField(
            model_name="tablet",
            name="name",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
