# Generated by Django 4.1.3 on 2023-12-12 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tablet", "0004_alter_tablet_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tablet",
            name="doctor",
        ),
        migrations.RemoveField(
            model_name="tablet",
            name="nurse",
        ),
    ]
