# Generated by Django 4.1.3 on 2024-01-28 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("settings", "0002_alter_area_name"),
        ("tablet", "0005_remove_tablet_doctor_remove_tablet_nurse"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tablet",
            name="area",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tablets",
                to="settings.area",
            ),
        ),
    ]
